//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hello_World.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public L_Group()
        {
            this.T_User = new HashSet<T_User>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDDepartment { get; set; }
        public string Title { get; set; }
        public Nullable<int> Course { get; set; }
    
        public virtual H_Department H_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_User> T_User { get; set; }
    }
}
