//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hello_World.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbHelloWorldEntities : DbContext
    {
        public dbHelloWorldEntities()
            : base("name=dbHelloWorldEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_Gender> A_Gender { get; set; }
        public virtual DbSet<H_Department> H_Department { get; set; }
        public virtual DbSet<L_Group> L_Group { get; set; }
        public virtual DbSet<T_User> T_User { get; set; }
    }
}
