//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hello_World.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string Instagram { get; set; }
        public string Phone { get; set; }
        public string Vk { get; set; }
        public string Image { get; set; }
        public string IDGender { get; set; }
        public int IDGroup { get; set; }
    
        public virtual A_Gender A_Gender { get; set; }
        public virtual L_Group L_Group { get; set; }
    }
}
