//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstToEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodService
    {
        public int ID { get; set; }
        public int BloodID { get; set; }
        public int ServiceCode { get; set; }
        public string result { get; set; }
        public System.DateTime finished { get; set; }
        public bool accepted { get; set; }
        public string status { get; set; }
        public int analyzerID { get; set; }
        public int UserId { get; set; }
    }
}
