//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstToEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Code { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
