//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBeginHate.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodService
    {
        public int ID { get; set; }
        public int BloodId { get; set; }
        public int ServiceID { get; set; }
        public string result { get; set; }
        public Nullable<System.DateTime> finished { get; set; }
        public Nullable<bool> accepted { get; set; }
        public string status { get; set; }
        public int analyzerID { get; set; }
        public int userID { get; set; }
    
        public virtual Analyzer Analyzer { get; set; }
        public virtual Blood Blood { get; set; }
        public virtual Service Service { get; set; }
    }
}
