//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBeginHate.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuraneCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsuraneCompany()
        {
            this.Patient = new HashSet<Patient>();
        }
    
        public int ID { get; set; }
        public string Countru { get; set; }
        public string Name { get; set; }
        public string address { get; set; }
        public string inn { get; set; }
        public string IP { get; set; }
        public string pc { get; set; }
        public string BIK { get; set; }
        public string UA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patient { get; set; }
    }
}
