//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBeginHate.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Blood = new HashSet<Blood>();
        }
    
        public int ID { get; set; }
        public string FirstNaem { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int DataID { get; set; }
        public Nullable<int> InsuraneID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blood> Blood { get; set; }
        public virtual InsuraneCompany InsuraneCompany { get; set; }
        public virtual PatientData PatientData { get; set; }
    }
}
