//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbAPI.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_Car
    {
        public int id { get; set; }
        public string car_num { get; set; }
        public string create_date { get; set; }
        public string licence_num { get; set; }
        public string photo { get; set; }
    }
}
